# http://docs.travis-ci.com/user/build-configuration/

services:
    - mysql

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install sqlalchemy
    - pip install Flask-SQLAlchemy
    - pip install pymysql
    - pip install gunicorn

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make check
    - make test