# http://docs.travis-ci.com/user/build-configuration/

dist: trusty
sudo: required
addons:
    apt:
        packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install gunicorn

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -u root -e "create database guestbook"

script:
    - date
    - ls -al
    - make check
    - make test